name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev/3.0.0             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: PaperMC/Velocity      # set the upstream repo
          upstream-branch: dev/3.0.0   # set the upstream branch to merge from
          branch: dev/3.0.0          # set the branch to merge to